name: Browserstack (Core 3.x)

on:
  push:
    branches:
      - main
  # Once a week every Tuesday
  schedule:
    - cron: "12 2 * * 2"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: browserstack
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      NODE_VERSION: 20.x
    name: ${{ matrix.BROWSER }}
    concurrency:
      group: ${{ matrix.BROWSER }} - ${{ github.sha }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        BROWSER:
          - 'IE_11'
          - 'IE_10'
          - 'IE_9'
          - 'Safari_latest'
          - 'Safari_latest-1'
          - 'Chrome_latest'
          - 'Chrome_latest-1'
          - 'Opera_latest'
          - 'Edge_latest'
          - 'Edge_latest-1'
          - 'Edge_18'
          - 'Firefox_latest'
          - 'Firefox_latest-1'
          - 'Firefox_115'
          - 'Firefox_102'
          - 'Firefox_91'
          - 'Firefox_78'
          - 'Firefox_60'
          - 'Firefox_48'
          - '__iOS_18'
          - '__iOS_17'
          - '__iOS_16'
          - '__iOS_15'
          - '__iOS_14'
          - '__iOS_13'
          - '__iOS_12'
          - '__iOS_11'
          - '__iOS_10'
          - '__iOS_9'
          - '__iOS_8'
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-npm-lock-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-npm-lock-

      - name: Install dependencies
        run: npm install

      - name: Pretest script
        run: npm run pretest

      - name: Test
        run: |
          npm run test:unit -- \
            -v --browserstack "${{ matrix.BROWSER }}" \
            --jquery-migrate dev --jquery-migrate min \
            --jquery 3.x-git --jquery 3.x-git.min --jquery 3.x-git.slim --jquery 3.x-git.slim.min \
            --jquery 3.7.1 --jquery 3.7.1.slim --jquery 3.6.4 --jquery 3.6.4.slim \
            --jquery 3.5.1 --jquery 3.5.1.slim --jquery 3.4.1 --jquery 3.4.1.slim \
            --jquery 3.3.1 --jquery 3.3.1.slim --jquery 3.2.1 --jquery 3.2.1.slim \
            --jquery 3.1.1 --jquery 3.1.1.slim --jquery 3.0.0 --jquery 3.0.0.slim \
            --run-id ${{ github.run_id }} \
            --retries 3 --hard-retries 1
